apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-memorymaster
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: memorymaster
  template:
    metadata:
      labels:
        app: memorymaster
    spec:
      containers:
        - name: memorymaster
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8765
          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-data
          {{- else }}
          emptyDir: {}
          {{- end }}
