apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-memorymaster
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8765
  selector:
    app: memorymaster
