"""Los tests no pisan el perfil compilado del operador.

QUE PASO (2026-08-24). `scheduled_task._run_dream` llama a
`run_compiled_profile(args.db)` sin `output_dir`, asi que la escritura cae en
`~/.memorymaster/projections/`. `MEMORYMASTER_COMPILED_PROFILE=1` esta puesta a
nivel usuario en esta maquina, de modo que correr
`tests/test_scheduled_task_runtime.py` ejecutaba ese camino con una base temporal
VACIA, renderizaba cero hechos y pisaba atomicamente el `user.md` real.

POR QUE NO LO VIO NADIE. Los tests pasaban. El unico sintoma era que el perfil
que se inyecta en cada SessionStart quedaba con 251 bytes y ninguna vinieta,
mientras la base tenia 29 hechos activos que renderizan en 788 tokens. Un test en
verde que destruye datos del operador no se parece a un fallo, se parece a exito.

ESTE ARCHIVO ES EL GUARD DEL FIXTURE, NO DEL MOTOR. `_hermetic_profile_projections`
en conftest.py es la proteccion; sin un test que lo ejercite seria una linea que
nadie comprueba, y la siguiente persona que la borre por parecer innecesaria no
veria ningun rojo. El test de abajo si se pone rojo.
"""
from __future__ import annotations

import hashlib
import os
from argparse import Namespace
from pathlib import Path

import pytest


PERFIL_REAL = Path.home() / ".memorymaster" / "projections" / "user.md"


def _huella(path: Path) -> tuple[bool, str, float]:
    if not path.exists():
        return (False, "", 0.0)
    datos = path.read_bytes()
    return (True, hashlib.sha256(datos).hexdigest(), path.stat().st_mtime)


def test_the_fixture_redirects_the_projection_dir():
    """El fixture autouse tiene que estar puesto y NO apuntar al home real."""
    configurado = os.environ.get("MEMORYMASTER_PROFILE_OUTPUT_DIR", "")
    assert configurado, "el fixture _hermetic_profile_projections no se aplico"
    assert Path(configurado).resolve() != PERFIL_REAL.parent.resolve(), (
        "el directorio de proyecciones de los tests es el REAL del operador"
    )


def test_running_the_scheduled_dream_path_leaves_the_real_profile_untouched(
    tmp_path, monkeypatch,
):
    """El caso exacto que causo el dano, ahora como regresion.

    Se ejerce el camino REAL —`_run_dream` con el flag encendido— y se comprueba
    que el archivo del operador no cambia. Anclado en la consecuencia (el archivo
    real intacto) y no en la implementacion: seguiria protegiendo aunque el motor
    cambie de nombre o de ruta interna.
    """
    from memorymaster.surfaces.scheduled_task import _run_dream

    monkeypatch.setenv("MEMORYMASTER_COMPILED_PROFILE", "1")
    # `improve` devuelve un objeto con to_dict(), no un dict: el camino real hace
    # `queued.to_dict()` al imprimir el resumen.
    monkeypatch.setattr(
        "memorymaster.public.v1.improve",
        lambda *a, **k: type("Q", (), {"to_dict": lambda self: {"ok": True}})(),
    )
    monkeypatch.setattr(
        "memorymaster.capture.worker.run_capture_worker",
        lambda *a, **k: type("R", (), {
            "leased": 0, "completed": 0, "retryable": 0,
            "blocked": 0, "errors": 0, "partial": False,
        })(),
    )
    monkeypatch.setattr(
        "memorymaster.dreaming.worker.run_dream",
        lambda *a, **k: {"ok": True, "errors": 0},
    )

    workspace = tmp_path / "ws"
    workspace.mkdir()
    antes = _huella(PERFIL_REAL)

    _run_dream(Namespace(
        db=str(tmp_path / "vacia.db"),
        workspace=str(workspace),
        apply_candidates=False,
    ))

    despues = _huella(PERFIL_REAL)
    assert despues == antes, (
        "el camino programado escribio sobre el perfil compilado REAL del "
        f"operador ({PERFIL_REAL}); antes={antes} despues={despues}"
    )


def test_the_env_override_is_honoured(tmp_path, monkeypatch):
    """Control negativo del override: apuntandolo a otro lado, escribe alli.

    Sin este caso, un override roto que nunca escribe nada pasaria igual el test
    de arriba — el perfil real quedaria intacto por la razon equivocada.
    """
    from memorymaster.profile.engine import CompiledProfileEngine
    from memorymaster.profile.repository import ProfileRepository

    destino = tmp_path / "salida"
    monkeypatch.setenv("MEMORYMASTER_PROFILE_OUTPUT_DIR", str(destino))

    from memorymaster.core.service import MemoryService

    db = tmp_path / "perfil.db"
    MemoryService(str(db), workspace_root=str(tmp_path)).init_db()

    engine = CompiledProfileEngine(
        ProfileRepository(str(db)), object(), object(), output_dir=destino,
    )
    from datetime import datetime, timezone
    engine._write_projection(datetime(2026, 8, 24, tzinfo=timezone.utc))

    assert (destino / "user.md").exists(), "el override no se uso"
    assert "generated by MemoryMaster" in (destino / "user.md").read_text(encoding="utf-8")


@pytest.mark.parametrize("nombre", ["user.md", "user-profile.json"])
def test_both_projection_artifacts_are_covered(nombre, tmp_path, monkeypatch):
    """El motor escribe DOS archivos; proteger solo uno deja el otro expuesto."""
    real = Path.home() / ".memorymaster" / "projections" / nombre
    configurado = Path(os.environ["MEMORYMASTER_PROFILE_OUTPUT_DIR"]).resolve()
    assert configurado != real.parent.resolve()
