from __future__ import annotations

import importlib.util
import io
import json
import subprocess
import sys
from pathlib import Path

import pytest


ROOT = Path(__file__).resolve().parents[1]
HOOK = ROOT / "memorymaster" / "config_templates" / "hooks" / "memorymaster-session-start.py"


def _hook_module():
    spec = importlib.util.spec_from_file_location("compiled_profile_session_hook", HOOK)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_session_start_loads_only_generated_bounded_profile(tmp_path: Path) -> None:
    module = _hook_module()
    profile = tmp_path / "user.md"
    module.PROFILE_PATH = profile
    profile.write_text(
        "<!-- generated by MemoryMaster; rebuild instead of editing -->\n"
        "# Compiled User Profile\n\n- The operator is based in Argentina.\n",
        encoding="utf-8",
    )

    loaded = module._load_compiled_profile()
    context = module._format_context("project:test", [], {}, 0, [], loaded)

    assert "Compiled User Profile" in loaded
    assert "MemoryMaster compiled user profile" in context
    profile.write_text("# hand-written file", encoding="utf-8")
    assert module._load_compiled_profile() == ""


def test_session_start_logs_integer_candidate_count_and_injects_profile(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    module = _hook_module()
    db = tmp_path / "memory.db"
    db.touch()
    profile = tmp_path / "user.md"
    profile.write_text(
        "<!-- generated by MemoryMaster; rebuild instead of editing -->\nprofile fact\n",
        encoding="utf-8",
    )
    logged: list[dict[str, object]] = []
    monkeypatch.setattr(module, "DB_PATH", db)
    monkeypatch.setattr(module, "PROFILE_PATH", profile)
    monkeypatch.setattr(module, "_query_recent_claims", lambda *_: [])
    monkeypatch.setattr(module, "_query_last_cycle_summary", lambda *_: {})
    monkeypatch.setattr(module, "_query_candidate_claims", lambda *_: 2)
    monkeypatch.setattr(module, "_load_recent_wiki_articles", lambda *_: [])
    monkeypatch.setattr(module, "_log", lambda _event, **values: logged.append(values))
    monkeypatch.setattr(sys, "stdin", io.StringIO("{}"))

    with pytest.raises(SystemExit) as stopped:
        module.main()

    payload = json.loads(capsys.readouterr().out)
    assert stopped.value.code == 0
    assert logged[-1]["candidates"] == 2
    assert "MemoryMaster compiled user profile" in payload["hookSpecificOutput"]["additionalContext"]


def test_profile_module_cli_status_and_help(tmp_path: Path) -> None:
    db = tmp_path / "profile.db"
    help_run = subprocess.run(
        [sys.executable, "-m", "memorymaster.profile", "--help"],
        capture_output=True,
        text=True,
        encoding="utf-8",
        timeout=20,
    )
    status_run = subprocess.run(
        [sys.executable, "-m", "memorymaster.profile", "status", "--db", str(db)],
        capture_output=True,
        text=True,
        encoding="utf-8",
        timeout=20,
    )

    assert help_run.returncode == 0
    assert "compiled user profile" in help_run.stdout.lower()
    assert status_run.returncode == 0
    payload = json.loads(status_run.stdout)
    assert payload == {"active_run": None, "facts": 0, "latest_completed_run": None}
