from __future__ import annotations

import importlib.util
import json
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
HOOK = ROOT / "memorymaster" / "config_templates" / "hooks" / "memorymaster-session-start.py"


def _hook_module():
    spec = importlib.util.spec_from_file_location("compiled_profile_session_hook", HOOK)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_session_start_loads_only_generated_bounded_profile(tmp_path: Path) -> None:
    module = _hook_module()
    profile = tmp_path / "user.md"
    module.PROFILE_PATH = profile
    profile.write_text(
        "<!-- generated by MemoryMaster; rebuild instead of editing -->\n"
        "# Compiled User Profile\n\n- The operator is based in Argentina.\n",
        encoding="utf-8",
    )

    loaded = module._load_compiled_profile()
    context = module._format_context("project:test", [], {}, 0, [], loaded)

    assert "Compiled User Profile" in loaded
    assert "MemoryMaster compiled user profile" in context
    profile.write_text("# hand-written file", encoding="utf-8")
    assert module._load_compiled_profile() == ""


def test_profile_module_cli_status_and_help(tmp_path: Path) -> None:
    db = tmp_path / "profile.db"
    help_run = subprocess.run(
        [sys.executable, "-m", "memorymaster.profile", "--help"],
        capture_output=True,
        text=True,
        encoding="utf-8",
        timeout=20,
    )
    status_run = subprocess.run(
        [sys.executable, "-m", "memorymaster.profile", "status", "--db", str(db)],
        capture_output=True,
        text=True,
        encoding="utf-8",
        timeout=20,
    )

    assert help_run.returncode == 0
    assert "compiled user profile" in help_run.stdout.lower()
    assert status_run.returncode == 0
    payload = json.loads(status_run.stdout)
    assert payload == {"active_run": None, "facts": 0, "latest_completed_run": None}
