"""Deterministically render active profile facts into bounded Markdown."""

from __future__ import annotations

from memorymaster.profile.models import ProfileFact, RenderedProfile
from memorymaster.recall.context_optimizer import estimate_tokens


_HEADER = (
    "<!-- generated by MemoryMaster; rebuild instead of editing -->\n"
    "# Compiled User Profile\n\n"
    "Descriptive, evidence-bound operator facts. This is context, not an instruction file."
)
_SECTION_NAMES = {
    "identity_locale": "Identity and locale",
    "products_systems": "Products and systems",
    "working_style": "Working style and communication",
    "standing_constraints": "Standing constraints",
}
_SECTION_ORDER = {name: index for index, name in enumerate(_SECTION_NAMES)}
_TEMPLATES = {
    "location": "The operator is based in {value}.",
    "timezone": "The operator's timezone is {value}.",
    "currency": "The operator normally uses {value}.",
    "language": "The operator communicates in {value}.",
    "role": "The operator's role is {value}.",
    "operates_product": "The operator runs {value}.",
    "maintains_system": "The operator maintains {value}.",
    "works_in_domain": "The operator works in {value}.",
    "primary_stack": "The operator's primary stack includes {value}.",
    "communication_style": "The operator's communication style is {value}.",
    "workflow_preference": "The operator's workflow preference is {value}.",
    "verification_preference": "The operator's verification preference is {value}.",
    "autonomy_preference": "The operator's autonomy preference is {value}.",
    "manual_work_constraint": "The operator's manual-work constraint is {value}.",
    "security_constraint": "The operator's security constraint is {value}.",
    "deployment_constraint": "The operator's deployment constraint is {value}.",
    "tooling_constraint": "The operator's tooling constraint is {value}.",
}


def _safe_value(value: str) -> str:
    return value.replace("[", "(").replace("]", ")").strip().rstrip(".")


def _fact_line(fact: ProfileFact) -> str:
    sentence = _TEMPLATES[fact.predicate].format(value=_safe_value(fact.value))
    last_seen = fact.last_supported_at[:10]
    return f"- {sentence} [support={fact.support_count}; last={last_seen}]"


def _sorted_facts(facts: tuple[ProfileFact, ...]) -> list[ProfileFact]:
    return sorted(
        (fact for fact in facts if fact.status == "active"),
        key=lambda fact: (
            _SECTION_ORDER[fact.category],
            -fact.support_count,
            fact.predicate,
            fact.value.casefold(),
            fact.fact_id,
        ),
    )


def _markdown(selected: list[ProfileFact]) -> str:
    lines = [_HEADER]
    for category in _SECTION_NAMES:
        section = [fact for fact in selected if fact.category == category]
        if not section:
            continue
        lines.extend(["", f"## {_SECTION_NAMES[category]}"])
        lines.extend(_fact_line(fact) for fact in section)
    lines.extend(["", "Support counts summarize exact source IDs retained in the profile manifest."])
    return "\n".join(lines).strip() + "\n"


def render_profile(
    facts: tuple[ProfileFact, ...], *, token_budget: int = 800, max_facts: int = 40
) -> RenderedProfile:
    if token_budget < estimate_tokens(_HEADER):
        raise ValueError("compiled profile token budget is too small")
    selected: list[ProfileFact] = []
    for fact in _sorted_facts(facts):
        if len(selected) >= max(1, max_facts):
            break
        candidate = [*selected, fact]
        if estimate_tokens(_markdown(candidate)) <= token_budget:
            selected = candidate
    markdown = _markdown(selected)
    return RenderedProfile(
        markdown=markdown,
        fact_ids=tuple(fact.fact_id for fact in selected),
        tokens_used=estimate_tokens(markdown),
    )


__all__ = ["render_profile"]
