"""Generate Obsidian Bases (.base YAML files) from wiki frontmatter.

Obsidian Bases are lightweight YAML that define dynamic views over note
frontmatter. They update automatically as notes change, so MemoryMaster
only needs to write the .base files once per wiki-absorb run.

Bases generated:
  - all-claims.base   — every wiki article, grouped by scope, sorted by date
  - gotchas.base      — articles with type=gotcha or gotcha tag
  - decisions.base    — articles with type=decision
  - recent.base       — articles updated in last 14 days
  - needs-review.base — articles with `description` missing or too short

Requires the Obsidian Bases core plugin to be enabled.
"""
from __future__ import annotations

import logging
from pathlib import Path

logger = logging.getLogger(__name__)


BASES_README = """# Wiki Bases

Dynamic dashboards generated by MemoryMaster. Open any `.base` file in
Obsidian to see a live, filterable view over your wiki articles.

Regenerate with: `python -m memorymaster bases-generate`
"""


def _base_all_claims() -> str:
    return """filters:
  and:
    - file.ext == "md"
    - file.path.startsWith("wiki")
properties:
  title:
    displayName: Title
  description:
    displayName: Description
  type:
    displayName: Type
  scope:
    displayName: Scope
  date:
    displayName: Date
views:
  - type: table
    name: All Articles
    order:
      - title
      - description
      - type
      - scope
      - date
    sort:
      - property: date
        direction: DESC
  - type: cards
    name: Cards
    order:
      - title
      - description
      - type
    sort:
      - property: date
        direction: DESC
"""


def _base_gotchas() -> str:
    return """filters:
  and:
    - file.ext == "md"
    - file.path.startsWith("wiki")
    - or:
        - type == "gotcha"
        - type == "bug"
        - tags.contains("gotcha")
        - tags.contains("bug")
properties:
  title:
    displayName: Gotcha
  description:
    displayName: What to watch out for
  scope:
    displayName: Scope
  date:
    displayName: Learned
views:
  - type: table
    name: Gotchas & Bugs
    order:
      - title
      - description
      - scope
      - date
    sort:
      - property: date
        direction: DESC
"""


def _base_decisions() -> str:
    return """filters:
  and:
    - file.ext == "md"
    - file.path.startsWith("wiki")
    - or:
        - type == "decision"
        - type == "architecture"
        - tags.contains("decision")
        - tags.contains("architecture")
properties:
  title:
    displayName: Decision
  description:
    displayName: What was decided
  scope:
    displayName: Scope
  date:
    displayName: Date
views:
  - type: table
    name: Decisions & Architecture
    order:
      - title
      - description
      - scope
      - date
    sort:
      - property: date
        direction: DESC
"""


def _base_recent() -> str:
    return """filters:
  and:
    - file.ext == "md"
    - file.path.startsWith("wiki")
    - file.mtime >= date(today).minus(14, "days")
properties:
  title:
    displayName: Title
  description:
    displayName: Description
  type:
    displayName: Type
  scope:
    displayName: Scope
  date:
    displayName: Updated
views:
  - type: table
    name: Recent (last 14 days)
    order:
      - title
      - description
      - type
      - scope
      - date
    sort:
      - property: file.mtime
        direction: DESC
"""


def _base_needs_review() -> str:
    return """filters:
  and:
    - file.ext == "md"
    - file.path.startsWith("wiki")
    - or:
        - 'description == ""'
        - 'description == null'
properties:
  title:
    displayName: Title
  type:
    displayName: Type
  scope:
    displayName: Scope
  date:
    displayName: Date
views:
  - type: table
    name: Needs Review (missing description)
    order:
      - title
      - type
      - scope
      - date
    sort:
      - property: date
        direction: DESC
"""


BASES: dict[str, str] = {
    "all-claims.base": _base_all_claims(),
    "gotchas.base": _base_gotchas(),
    "decisions.base": _base_decisions(),
    "recent.base": _base_recent(),
    "needs-review.base": _base_needs_review(),
}


def generate_bases(vault_root: str | Path) -> dict:
    """Write all .base files under <vault_root>/bases/.

    Returns {"written": N, "path": str}. Safe to call multiple times;
    overwrites existing files (they are generated, not user-edited).
    """
    vault = Path(vault_root)
    bases_dir = vault / "bases"
    bases_dir.mkdir(parents=True, exist_ok=True)

    written = 0
    for filename, content in BASES.items():
        target = bases_dir / filename
        target.write_text(content, encoding="utf-8")
        written += 1

    readme = bases_dir / "README.md"
    readme.write_text(BASES_README, encoding="utf-8")

    return {
        "written": written,
        "path": str(bases_dir),
        "files": list(BASES.keys()),
    }
