"""Generate deterministic release facts from executable project sources."""

from __future__ import annotations

import argparse
import importlib.metadata
import json
from pathlib import Path
import re
import subprocess
import sys
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


def _project_version() -> str:
    text = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
    match = re.search(r'^version\s*=\s*"([^"]+)"', text, re.MULTILINE)
    if match is None:
        raise RuntimeError("project.version is missing from pyproject.toml")
    return match.group(1)


def _command_names(parser: Any) -> list[str]:
    import argparse as argparse_module

    actions = (action for action in parser._actions if isinstance(action, argparse_module._SubParsersAction))
    subparsers = next(actions, None)
    return sorted(subparsers.choices) if subparsers is not None else []


def _pytest_count() -> int:
    result = subprocess.run(
        [sys.executable, "-m", "pytest", "tests", "--collect-only", "-q"],
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
        timeout=240,
    )
    output = f"{result.stdout}\n{result.stderr}"
    matches = re.findall(r"(\d+) tests? collected", output)
    if result.returncode != 0 or not matches:
        raise RuntimeError(f"pytest collection failed ({result.returncode}): {output[-1200:]}")
    return int(matches[-1])


def _release_truth() -> dict[str, Any]:
    import memorymaster
    from memorymaster.surfaces import mcp_server
    from memorymaster.surfaces.cli import build_parser
    from memorymaster.surfaces.operations import _build_parser as build_ops_parser
    from memorymaster.surfaces.setup_hooks import SETUP_PROFILES

    source_version = _project_version()
    installed_version = importlib.metadata.version("memorymaster")
    if {source_version, installed_version, memorymaster.__version__} != {source_version}:
        raise RuntimeError("source, installed, and runtime package versions differ")
    profiles = {name: list(components) for name, components in sorted(SETUP_PROFILES.items())}
    components = sorted({component for values in profiles.values() for component in values})
    distribution = importlib.metadata.distribution("memorymaster")
    entrypoints = sorted(item.name for item in distribution.entry_points if item.group == "console_scripts")
    return {
        "version": source_version,
        "counts": {
            "mcp_tools": len(mcp_server.mcp._tool_manager.list_tools()),
            "cli_commands": len(_command_names(build_parser())),
            "ops_cli_commands": len(_command_names(build_ops_parser())),
            "console_entrypoints": len(entrypoints),
            "pytest_tests": _pytest_count(),
        },
        "mcp_tools": sorted(tool.name for tool in mcp_server.mcp._tool_manager.list_tools()),
        "cli_commands": _command_names(build_parser()),
        "ops_cli_commands": _command_names(build_ops_parser()),
        "console_entrypoints": entrypoints,
        "setup_profiles": profiles,
        "feature_profile_matrix": {
            component: [name for name, values in profiles.items() if component in values]
            for component in components
        },
    }


def _markdown(data: dict[str, Any]) -> str:
    counts = data["counts"]
    lines = [
        "# Generated release truth",
        "",
        "Do not edit this file by hand. Run `python scripts/generate_release_truth.py`.",
        "",
        f"- Package version: `{data['version']}`",
        f"- MCP tools: **{counts['mcp_tools']}**",
        f"- Main CLI commands: **{counts['cli_commands']}**",
        f"- Operations CLI commands: **{counts['ops_cli_commands']}**",
        f"- Console entrypoints: **{counts['console_entrypoints']}**",
        f"- Collected pytest tests: **{counts['pytest_tests']}**",
        "",
        "## MCP tools",
        "",
        ", ".join(f"`{name}`" for name in data["mcp_tools"]),
        "",
        "## Setup feature/profile matrix",
        "",
        "| Component | Required by profiles |",
        "|---|---|",
    ]
    for component, profiles in data["feature_profile_matrix"].items():
        lines.append(f"| `{component}` | {', '.join(f'`{name}`' for name in profiles)} |")
    lines.extend(["", "## Console entrypoints", "", ", ".join(f"`{name}`" for name in data["console_entrypoints"]), ""])
    return "\n".join(lines)


def _write_or_check(path: Path, content: str, check: bool) -> bool:
    if check:
        return path.is_file() and path.read_text(encoding="utf-8") == content
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if committed generated truth has drifted.")
    args = parser.parse_args()
    data = _release_truth()
    outputs = {
        ROOT / "docs/generated/release-truth.json": json.dumps(data, indent=2, sort_keys=True) + "\n",
        ROOT / "docs/generated/release-truth.md": _markdown(data),
    }
    drifted = [str(path.relative_to(ROOT)) for path, content in outputs.items() if not _write_or_check(path, content, args.check)]
    if drifted:
        print("Generated release truth is stale: " + ", ".join(drifted), file=sys.stderr)
        return 1
    print("Release truth verified." if args.check else "Release truth generated.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
